version: 2

build: 
  image: latest

conda:
  environment: environment-docs.yml

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

python:
  version: 3.8
  system_packages: false
  install:
    - method: pip
      path: .

formats: []
